apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wacopro-production

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: wacopro-backend
    patch: |-
      - op: replace
        path: /spec/template/spec/nodeSelector
        value:
          topology.kubernetes.io/region: ap-southeast-1
  - target:
      kind: HorizontalPodAutoscaler
      name: wacopro-backend
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 2
      - op: replace
        path: /spec/maxReplicas
        value: 30

configMapGenerator:
  - name: wacopro-config
    behavior: merge
    literals:
      - REGION=ap-southeast-1
      - API_URL=https://ap.wacopro.com
      - CDN_ENDPOINT=https://ap.cdn.wacopro.com

images:
  - name: ghcr.io/wacopro/backend
    newTag: "latest"
